In [8]:
import cv2
import numpy as np

In [9]:

image = cv2.imread('original_images/frame18757.jpg')

# Print error message if image is null
if image is None:
    print('Could not read image')


In [10]:
# Apply identity kernel
kernel1 = np.array([[0, 0, 0],
                    [0, 1, 0],
                    [0, 0, 0]])

identity = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)

In [11]:
cv2.imshow('Original', image)
cv2.imshow('Identity', identity)
cv2.waitKey()
#cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()

In [14]:
# Apply blurring kernel
kernel2 = np.ones((5, 5), np.float32) / 25
print(kernel2)
img = cv2.filter2D(src=image, ddepth=-1, kernel=kernel2)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [13]:
cv2.imshow('Original', image)
cv2.imshow('Kernel Blur', img)
    
cv2.waitKey()
#cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()

In [17]:
#using the blur function - Average Blur

img_blur = cv2.blur(src=image, ksize=(15,15)) # Using the blur function to blur an image where ksize is the kernel size

In [18]:
cv2.imshow('Original', image)
cv2.imshow('Blur func', img_blur)
    
cv2.waitKey()
#cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()

In [21]:
# Gaussian Blur
gaussian_blur = cv2.GaussianBlur(src=image, ksize=(5,5), sigmaX=0, sigmaY=0)

In [22]:
cv2.imshow('Original', image)
cv2.imshow('Gausssian Blur', gaussian_blur)
    
cv2.waitKey()
#cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()

In [24]:
# Median Blur
median_blur = cv2.medianBlur(src=image, ksize=5)

In [25]:
cv2.imshow('Original', image)
cv2.imshow('Median Blur', median_blur)
    
cv2.waitKey()
#cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()