In [40]:
import cv2
import numpy as np

In [41]:

image = cv2.imread('original_images/frame18757.jpg')

# Print error message if image is null
if image is None:
    print('Could not read image')


In [42]:
cv2.imshow('Original', image)
cv2.waitKey()
#cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()

In [43]:
# Apply identity kernel
kernel1 = np.array([[0, 0, 0],
                    [0, 1, 0],
                    [0, 0, 0]])

identity = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)

In [44]:
kernel3 = np.array([[1, 0, 1],
                    [0, 1, 0],
                    [1, 0, 1]])

identity_3 = cv2.filter2D(src=image, ddepth=-1, kernel=kernel3)

In [45]:
cv2.imshow('Original', image)
cv2.imshow('Identity', identity)
cv2.imshow('Identity3', identity_3)
cv2.waitKey()
#cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()

In [46]:
# Apply blurring kernel
kernel2 = np.ones((5, 5), np.float32) / 25
print(kernel2)
img = cv2.filter2D(src=image, ddepth=-1, kernel=kernel2)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [47]:
cv2.imshow('Original', image)
cv2.imshow('Kernel Blur', img)
    
cv2.waitKey()
#cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()

In [48]:
#using the blur function - Average Blur

img_blur = cv2.blur(src=image, ksize=(3,3)) # Using the blur function to blur an image where ksize is the kernel size

In [49]:
cv2.imshow('Original', image)
cv2.imshow('Blur func', img_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/average_filter_3.jpg', img_blur)
cv2.destroyAllWindows()

In [50]:
# Gaussian Blur
gaussian_blur = cv2.GaussianBlur(src=image, ksize=(3,3), sigmaX=0, sigmaY=0)

In [51]:
cv2.imshow('Original', image)
cv2.imshow('Gausssian Blur', gaussian_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/gaussian_filter_3.jpg', gaussian_blur)
cv2.destroyAllWindows()

In [52]:
# Median Blur
median_blur = cv2.medianBlur(src=image, ksize=3)

In [53]:
cv2.imshow('Original', image)
cv2.imshow('Median Blur', median_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/median_filter_3.jpg', median_blur)
cv2.destroyAllWindows()

Changing the Values to 7X7

In [54]:
#using the blur function - Average Blur

img_blur = cv2.blur(src=image, ksize=(7,7)) # Using the blur function to blur an image where ksize is the kernel size

cv2.imshow('Original', image)
cv2.imshow('Blur func', img_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/average_filter_7.jpg', img_blur)
cv2.destroyAllWindows()

In [55]:
# Gaussian Blur
gaussian_blur = cv2.GaussianBlur(src=image, ksize=(7,7), sigmaX=0, sigmaY=0)

cv2.imshow('Original', image)
cv2.imshow('Gausssian Blur', gaussian_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/gaussian_filter_7.jpg', gaussian_blur)
cv2.destroyAllWindows()

In [56]:
# Median Blur
median_blur = cv2.medianBlur(src=image, ksize=7)

cv2.imshow('Original', image)
cv2.imshow('Median Blur', median_blur)
    
cv2.waitKey()
cv2.imwrite('new_images/median_filter_7.jpg', median_blur)
cv2.destroyAllWindows()